### ISSUE TITLE
Complete BQSR subworkflow

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/gatk-mutect2-variant-calling#1]
implementation of BQSR workflow in WDL is included here: https://github.com/gatk-workflows/gatk4-genome-processing-pipeline/blob/master/tasks/UnmappedBamToAlignedBam.wdl, specific steps are here: https://github.com/gatk-workflows/gatk4-genome-processing-pipeline/blob/master/tasks/BamProcessing.wdl.

We can use this as reference to implement them in Nextflow:
- [x] nextflow sub-workflow (this repo)
- [x] BaseRecalibrator module in `gatk-tools` repo (icgc-argo/gatk-tools#30)
- [x] ApplyBQSR module in `gatk-tools` repo (icgc-argo/gatk-tools#31)
- [x] GatherBQSRReports module in `gatk-tools` repo (icgc-argo/gatk-tools#34)

**Comment by junjun-zhang** [comment]
done
