### ISSUE TITLE
Complete calculate-contamination NF sub-workflow

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/gatk-mutect2-variant-calling#2]
this includes:
- [x] NF subworkflow in this repo
- [x] GetPileupSummaries module in `gatk-tools` (icgc-argo/gatk-tools#32)
- [x] GatherPileupSummaries NF module in `gatk-tools` (icgc-argo/gatk-tools#33)
- [x] CalculateContamination NF module in `gatk-tools` (icgc-argo/gatk-tools#36)

**Comment by junjun-zhang** [comment]
need to have `variants_for_contamination` vcf as input, this can be produced from `af-only-gnomad.hg38.vcf.gz` (which is produced by Broad) by filtering out multi-allelic variants
